version: '2'
services:
  nginx:
      image: nginx:1.11
      container_name: md-web
      ports:
        - "8080:80"
      volumes:
#        - ./app/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./app/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www/html
      depends_on:
        - db
        - php
      networks:
        base_net:

  php:
    build: ./app/docker/php/php7.0-fpm
    container_name: md-php
    ports:
      - "9000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      base_net:
        ipv4_address: 172.16.238.11

  db:
    image: mysql:5.7
    container_name: md-db
    volumes:
      - ./app/docker/mysql/local.cnf:/etc/mysql/conf.d/local.cnf
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: music-diff
    networks:
      base_net:
        ipv4_address: 172.16.238.10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: md-pma
    ports:
      - "8090:80"
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: 172.16.238.10
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      base_net:

networks:
  base_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
