# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#
# Beware of inheritance in services, A extends B. If you want to add a setter of a parameter to constructor - you will
# have to override both services.

    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ['@fos_user.user_manager', {google: googleId, facebook: facebookId}]

# MusicDiff
    http_client:
        class: GuzzleHttp\Client

    music_brainz.http_adapter:
        class: MusicBrainz\HttpAdapters\GuzzleSixAdapter
        arguments: ['@http_client']
        public: false

    music_brainz.client:
        class: MusicBrainz\MusicBrainz
        arguments: ['@music_brainz.http_adapter']
        calls:
            - [setUserAgent, ['%music_brainz.application%', '%music_brainz.version%', '%music_brainz.contact_info%']]

    music_diff.data_provider.muzic_brainz:
        class: MusicDiff\DataProvider\MusicBrainz
        arguments: ['@music_brainz.client']
        public: false

    music_diff.data_provider.doctrine:
        class: MusicDiff\DataProvider\Doctrine
        arguments: ['@doctrine']
        calls:
            - [setNext, ['@music_diff.data_provider.muzic_brainz']]
        public: false

    music_diff:
        class: MusicDiff\MusicDiff
        arguments: ['@music_diff.data_provider.doctrine']

# Aspects
    aspect.logging:
        class: AppBundle\Aspect\LoggingAspect
        arguments: ["@logger"]
        tags:
            - { name: goaop.aspect }

    aspect.caching:
        class: AppBundle\Aspect\CachingAspect
        arguments: ["@doctrine_cache.default_provider", "@logger"]
        tags:
            - { name: goaop.aspect }
